name: Proiecte_Android_Flutter
description: A new Flutter project. This is the demo project for Google Programming Hub Flutter Course 1.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: any
  pedantic: ^1.9.2
  built_value: ^7.1.0
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  built_collection: ^4.3.2
  freezed_annotation: any

  cupertino_icons: ^1.0.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: '>=1.0.0 <2.0.0'
  built_value_generator: ^7.1.0
  freezed: any
  analyzer: any

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/audio/0_salut_romana.mp3
    - assets/audio/1_salut_germana.mp3
    - assets/audio/2_maNumesc_romana.mp3
    - assets/audio/3_maNumesc_germana.mp3
    - assets/audio/4_cumEsti_romana.mp3
    - assets/audio/5_cumEsti_germana.mp3
    - assets/audio/6_suntBine_romana.mp3
    - assets/audio/7_suntBine_germana.mp3


  uses-material-design: true

